# Generated by Django 2.2.9 on 2020-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='types_videos',
        ),
        migrations.AddField(
            model_name='video',
            name='type_video',
            field=models.CharField(choices=[('Animation', 'Animation'), ('Biopic', 'Biopic'), ('Comédie', 'Comédie'), ('Documentaire', 'Documentaire'), ('Drame', 'Drame'), ('Fantastique', 'Fantastique'), ('Science-fiction', 'Science-fiction'), ('Horreur', 'Horreur'), ('Guerre', 'Guerre'), ('Histoire', 'Biopic'), ('Policier', 'Policier'), ('Thriller', 'Thriller'), ('Aventure', 'Aventure')], default='Film', max_length=10),
        ),
    ]
