# Generated by Django 2.2.9 on 2020-01-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20200118_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default="default.png", upload_to=''),
            preserve_default=False,
        ),
    ]
